AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  phone-format-sam

  SAM Template for phone-format-sam
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PhoneFormatSamFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./phone-format-sam
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PhoneFormatSamApi:
    Description: "API Gateway endpoint URL for Prod stage for phone format function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/phone/"
  PhoneFormatSamFunction:
    Description: "Phone format Lambda Function ARN"
    Value: !GetAtt PhoneFormatSamFunction.Arn
  PhoneFormatSamFunctionIamRole:
    Description: "Implicit IAM Role created for Phone format function"
    Value: !GetAtt PhoneFormatSamFunctionRole.Arn
