AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  phone-format-sam

  SAM Template for phone-format-sam
  
Globals:
  Function:
    Timeout: 3

Resources:
  PhoneFormatSamFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Format:
          Type: Api
          Properties:
            Path: /format
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./phone-format-sam
      Dockerfile: Dockerfile

Outputs:
  PhoneFormatSamApi:
    Description: "API Gateway endpoint URL for Prod stage for phone format function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/format?PHONE=1234567890"
  PhoneFormatSamFunction:
    Description: "Phone format Lambda Function ARN"
    Value: !GetAtt PhoneFormatSamFunction.Arn
  PhoneFormatSamFunctionIamRole:
    Description: "Implicit IAM Role created for Phone format function"
    Value: !GetAtt PhoneFormatSamFunctionRole.Arn
